In [1]:
%%bash
cat >> requirements.txt
atari-py
gym
numpy
opencv-python
tensorboard
torch
torchvision
pytorch-ignite
tensorboardX
tensorflow
nltk
pybullet
ptan
matplotlib
gym-notebook-wrapper
pyvirtualdisplay
PyOpenGL
PyOpenGL-accelerate

In [4]:
%%bash
apt-get upgrade
apt-get update

apt-get install -y --no-install-recommends \
       apt-utils \
       build-essential \
       curl \
       xvfb \
       ffmpeg \
       xorg-dev \
       libsdl2-dev \
       swig \
       cmake \
       python-opengl

pip install  -r requirements.txt

Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  libcudnn8 libcudnn8-dev libnccl-dev libnccl2
The following packages will be upgraded:
  binutils binutils-common binutils-x86-64-linux-gnu cuda-compat-11-0 gnupg2
  libaudit-common libaudit1 libbinutils libc-bin libcublas-dev libcublas10
  libcudnn7 libcudnn7-dev libldap-2.4-2 libldap-common libp11-kit0 libperl5.26
  libsasl2-2 libsasl2-modules-db libzstd1 linux-libc-dev openssl perl
  perl-base perl-modules-5.26 tar ubuntu-keyring
27 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Need to get 460 MB of archives.
After this operation, 70.0 MB of additional disk space will be used.
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  cuda-compat-11-0 450.102.04-1 [6,712 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libperl5.26 amd64 5.26.1-6ubuntu0.5 [3,534 kB]
Get:3 https:/

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-140.144_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?


In [5]:
import pyvirtualdisplay
_display = pyvirtualdisplay.Display(visible=False, size=(1400, 900))
_ = _display.start()


# CODE HERE

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
